global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
- name: 'default'
  email_configs:
  - to: 'your-email@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'user@example.com'
    auth_password: 'password'
    auth_identity: 'user@example.com'
    require_tls: true
