global:
  scrape_interval: 15s

evaluation_interval: 15s
rule_files:
  - "/etc/prometheus/rules/alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'telegraf'
    static_configs:
      - targets: ['localhost:9273']
