groups:
- name: instance-alerts
  rules:
  - alert: HighCPUUsage
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"

  - alert: LowDiskSpace
    expr: (node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Low disk space on {{ $labels.instance }}"

  - alert: HighMemoryUsage
    expr: (node_memory_Active_bytes / node_memory_MemTotal_bytes) > 0.85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"

  - alert: OldFilesDetected
    expr: custom_files_old_count > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Old files detected on {{ $labels.instance }}"
